---
allow:
  # We use the technical term "host" a lot:
  - host-hostess
  - hostesses-hosts
  # It's about the language:
  - german
  - execute
  - executed
  - special
  - simple
  - crash
  - period
  - color
  - easy
  # Development-related:
  - hook
  - hooks
  - spa
