FROM python:3-alpine

WORKDIR /usr/src/app

VOLUME /usr/src/app

COPY requirements.txt /usr/src/app/

RUN apk add --no-cache \
        gcc \
        git \
        musl-dev; \
    pip install -U -r requirements.txt

CMD ["mkdocs", "--help"]
