---
services:

  env:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    image: docs/environment:main
    volumes:
      - "${PWD}:/runner/"
      - home:/home/runner
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp

volumes:
  home:
