FROM python:3-alpine

WORKDIR /usr/src/app

VOLUME /usr/src/app

RUN apk add --no-cache \
        gcc \
        git \
        musl-dev

COPY requirements.txt /usr/src/app/

RUN python --version; \
    pip --version; \
    pip install --no-cache-dir -r requirements.txt

CMD ["mkdocs", "--help"]
