---
version: "3.8"

services:

  docs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    image: docs/environment:main
    volumes:
      - "${PWD}:/runner/"
      - home:/home/runner
    cap_drop:
      - ALL

volumes:
  home:
