---
services:

  env:
    hostname: docs
    build:
      context: .
      dockerfile: Dockerfile
    image: ${REGISTRY_PREFIX:-}docs/environment:main
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    volumes:
      - "${PWD}:/runner/"
      - home:/home/runner
      - "${SSH_KEY_DOCS:-~/.ssh/cloud-production}:/etc/ssh/keys/docs:ro"
      - "${SSH_KEY_DOCS:-~/.ssh/cloud-production}.pub:/etc/ssh/keys/docs.pub:ro"
      - ${SSH_AUTH_SOCK:-/bin/true}:/ssh-agent
      - /var/run/docker.sock:/var/run/docker.sock
    cap_drop:
      - ALL
    privileged: false
    read_only: true
    tmpfs:
      - /tmp

  web:
    build:
      context: ./web/
    image: ${REGISTRY_PREFIX:-}docs/web:main
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test: curl --fail --user-agent 'healthcheck' http://localhost:8080/healthz
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    user: 101:101
    privileged: false
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    volumes:
      - ./site/:/usr/local/share/site/:ro
    develop:
      watch:
        - action: rebuild
          path: ./web/

volumes:
  home:
