---
site_name: docupike docs
site_url: https://docs.docupike.com/
site_description: The easy cloud based documentation
site_author: synetics GmbH
copyright: Copyright &copy; 2019-23 synetics GmbH
repo_url: https://github.com/docupike/docs
edit_uri: edit/main/docs/
strict: true
theme:
  name: material
  custom_dir: theme
  palette:
    - scheme: default
      primary: black
      accent: red
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font: false
  logo: img/logo.svg
  language: en
  favicon: favicon.ico
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.sections
    - navigation.top
    - search.suggest
extra_javascript:
  - js/status.js
extra_css:
  - css/status.css
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: iso_date
      strict: false
  - macros:
      module_name: announcements
      include_yaml:
        - data/announcements.yml
markdown_extensions:
  - admonition
  - attr_list
  - meta
  - toc:
      permalink: "#"
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      linenums_style: table
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
extra:
  manifest: manifest.webmanifest
  # social:
  #   - name: i-doit on Twitter
  #     link: https://twitter.com/i_doit
  #     icon: fontawesome/brands/twitter
  #   - name: i-doit on YouTube (English)
  #     link: https://www.youtube.com/channel/UC5wvDZjCslEWW2jE6R_5CUg
  #     icon: fontawesome/brands/youtube
  #   - name: i-doit on LinkedIn
  #     link: https://www.linkedin.com/company/1097514/
  #     icon: fontawesome/brands/linkedin
  #   - name: i-doit on Facebook
  #     link: https://facebook.com/itdokumentation/
  #     icon: fontawesome/brands/facebook
  #   - name: i-doit on GitHub
  #     link: https://github.com/i-doit
  #     icon: fontawesome/brands/github
use_directory_urls: false
watch:
  - data
  - docs
  - templates
  - theme
nav:
  - Overview: index.md
  - User guide:
      - Login: user/login.md
      - Documentation basics:
          - Classes: user/basics/classes.md
          - Collections: user/basics/collections.md
          - Categories and attributes: user/basics/categories-and-attributes.md
          - Enable or disable attributes: user/basics/enable-disable-attributes.md
          - Menu bar: user/basics/menubar.md
          - Objects: user/basics/objects.md
      - Finder:
          - Inline editing: user/finder/inline-editing.md
          - Multi editing: user/finder/multi-editing.md
          - Search filters and reports: user/finder/search-filters-and-reports.md
          - Views and presets: user/finder/views-and-presets.md
          - Widgets: user/finder/widgets.md
      - Reporting: user/reporting.md
      - Data protection: user/basics/gdpr.md
      - Documents Creator: user/basics/documents-creator.md
      - Imports:
          - CSV: user/imports/csv.md
      - Use cases:
          - Documentation and naming conventions: user/usecases/it-documentation-and-naming-conventions.md
          - How to Start: user/usecases/how-to-start.md
          - Import your first csv file: user/usecases/import-data.md
          - Locations: user/usecases/locations.md
          - Quick Edit in Lists: user/usecases/quick-edit-in-lists.md
          - Rights assignment: user/usecases/rights-assignment.md
          - Reports: user/usecases/reports.md
          - Workplace documentation: user/usecases/workplace-documentation.md
  - Admin guide:
      - Creating custom Categories: admin/custom-categories.md
      - Create custom classes: admin/custom-classes.md
      - Attribute validation: admin/attribute-validation.md
      - Export Data: admin/export-data.md
      - Rights and permissions: admin/rights-and-permissions.md
      - Users, groups and roles: admin/users-groups-roles.md
      - servereye integration: admin/servereye.md
  - Developer guide:
      - API: dev/api.md
      - Add-ons:
          - Introduction: dev/addon/introduction.md
          - Getting Started: dev/addon/quick-start.md
          - Frontend: dev/addon/frontend.md
          - JS Interface: dev/addon/js-api.md
          - CMDB Structures: dev/addon/cmdb-structures.md
          - API-CRUD: dev/addon/api-crud.md
          - Settings: dev/addon/settings.md
          - Add-on Endpoints: dev/addon/addon-endpoints.md
          - Licensing: dev/addon/licensing.md
          - Useful Resources: dev/addon/useful-resources.md
  - Technical reference:
      - System requirements: ref/system-requirements.md
      - Version history: ref/version-history.md
  - Announcements: announcements.md
