---
site_name: docupike docs
site_url: https://docs.docupike.com/
site_description: Documentation of things with docupike
site_author: synetics GmbH
copyright: Copyright &copy; 2019-22 synetics GmbH
repo_url: https://github.com/docupike/docs
edit_uri: edit/main/docs/
strict: true
theme:
  name: material
  custom_dir: theme
  palette:
    - scheme: default
      primary: black
      accent: red
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font: false
  logo: img/logo.svg
  language: en
  favicon: favicon.ico
  features:
    - search.suggest
    - navigation.sections
    - navigation.top
extra_javascript:
  - js/status.js
extra_css:
  - css/status.css
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: iso_date
  - macros:
      module_name: announcements
      include_yaml:
        - data/announcements.yml
markdown_extensions:
  - admonition
  - attr_list
  - meta
  - toc:
      permalink: "#"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      linenums_style: table
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
extra:
  manifest: manifest.webmanifest
  # social:
  #   - name: i-doit on Twitter
  #     link: https://twitter.com/i_doit
  #     icon: fontawesome/brands/twitter
  #   - name: i-doit on YouTube (English)
  #     link: https://www.youtube.com/channel/UC5wvDZjCslEWW2jE6R_5CUg
  #     icon: fontawesome/brands/youtube
  #   - name: i-doit on LinkedIn
  #     link: https://www.linkedin.com/company/1097514/
  #     icon: fontawesome/brands/linkedin
  #   - name: i-doit on Facebook
  #     link: https://facebook.com/itdokumentation/
  #     icon: fontawesome/brands/facebook
  #   - name: i-doit on GitHub
  #     link: https://github.com/i-doit
  #     icon: fontawesome/brands/github
use_directory_urls: false
watch:
  - data
  - docs
  - templates
  - theme
nav:
  - Overview: index.md
  - User guide:
      - Login: user/login.md
      - Documentation basics:
          - Classes: user/basics/classes.md
          - Collections: user/basics/collections.md
          - Categories and attributes: user/basics/categories-and-attributes.md
          - Objects: user/basics/objects.md
      - Finder:
          - Inline editing: user/finder/inline-editing.md
          - Multi editing: user/finder/multi-editing.md
          - Search filters and reports: user/finder/search-filters-and-reports.md
          - Views and presets: user/finder/views-and-presets.md
          - Widgets: user/finder/widgets.md
      - Reporting: user/reporting.md
      - Imports:
          - CSV: user/imports/csv.md
      - Use cases:
          - Locations: user/usecases/locations.md
          - Rights assignment: user/usecases/rights-assignment.md
  - Admin guide:
      - Createing custom Categories: admin/custom-categories.md
      - Create custom classes: admin/custom-classes.md
      - Export Data: admin/export-data.md
      - Rights and permissions: admin/rights-and-permissions.md
      - Users, groups and roles: admin/users-groups-roles.md
  - Developer guide:
      - API: dev/api.md
  - Technical reference:
      - System requirements: ref/system-requirements.md
      - Version history: ref/version-history.md
  - Announcements: announcements.md
