---
site_name: i-doit.cloud docs
site_url: https://docs.i-doit.cloud/
site_description: Documentation of things with i-doit.cloud
site_author: synetics GmbH
copyright: Copyright &copy; 2019-21
repo_url: https://github.com/i-doit/docs
strict: true
theme:
  name: material
  custom_dir: theme
  palette:
    - scheme: default
      primary: black
      accent: red
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font: false
  logo: img/i-doit-icon.png
  language: en
  favicon: img/favicon.png
  features:
    - search.suggest
    - navigation.sections
    - navigation.top
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: iso_date
markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      linenums: true
      linenums_style: table
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
extra:
  manifest: manifest.webmanifest
  social:
    - name: i-doit on Twitter
      link: https://twitter.com/i_doit
      icon: fontawesome/brands/twitter
    - name: i-doit on YouTube (English)
      link: https://www.youtube.com/channel/UC5wvDZjCslEWW2jE6R_5CUg
      icon: fontawesome/brands/youtube
    - name: i-doit on LinkedIn
      link: https://www.linkedin.com/company/1097514/
      icon: fontawesome/brands/linkedin
    - name: i-doit on Facebook
      link: https://facebook.com/itdokumentation/
      icon: fontawesome/brands/facebook
    - name: i-doit on GitHub
      link: https://github.com/i-doit
      icon: fontawesome/brands/github
use_directory_urls: false
nav:
  - Overview: index.md
  - User Guide:
      - Login: user/login.md
      # - Dashboard: user/dashboard.md
      - Objects:
          - Create and edit: user/objects/create-and-edit.md
          - Archive, delete, purge and restore: user/objects/archive-delete-purge-and-restore.md
          - History: user/objects/history.md
      - Documentation basics:
          - Collections: user/basics/collections.md
          - Classes: user/basics/classes.md
          - Objects: user/basics/objects.md
          - Categories and attributes: user/basics/categories-and-attributes.md
      - Finder:
          - Views and presets: user/finder/views-and-presets.md
          - Search filter and reports: user/finder/search-filter-and-reports.md
          # - Export and print: user/finder/export-and-print.md
          - Inline editing: user/finder/inline-editing.md
          - Multi editing: user/finder/multi-editing.md
      - Imports:
          - CSV: user/imports/csv.md
      # - User settings: user/settings.md
      # - Examples:
      #     - Server hardware: user/examples/server-hardware.md
  - Admin Guide:
      - Users and roles: admin/users-and-roles.md
      # - Documentation settings:
      #     - Collections: admin/documentation-settings/collections.md
      #     - Classes: admin/documentation-settings/classes.md
      #     - Categories: admin/documentation-settings/categories.md
      # - System settings: admin/system-settings.md
      # - Distribution Center: admin/distribution-center.md
#  - Installation:
#      - Installation:
#          - Manual Instructions:
#              - Debian: installation/debian.md
#              - Red Hat Enterprise Linux (RHEL): installation/rhel.md
#              - Ubuntu: installation/ubuntu.md
#              - Suse Linux Enterprise Server (SLES): installation/sles.md
#              - Microsoft Windows Server: installation/windows.md
#              - OS Settings: installation/os-settings.md
#              - Setup: installation/setup.md
#          - Docker Container: installation/docker-container.md
#          - Virtual Appliance: installation/virtual-appliance.md
#      - Maintenance:
#          - Subscriptions: installation/subscriptions.md
#          - Cronjobs: installation/cronjobs.md
#          - Backup and Recovery: installation/backup-and-recovery.md
#          - Updates: installation/updates.md
#          - Security: installation/security.md
#          - Performance: installation/performance.md
#          - Maintenance Mode: installation/maintenance-mode.md
#      - Migration:
#          - Migrate from 1.x to 2.x: installation/migrate-from-1.x-to-2.x.md
#      - Command-line interface (CLI): installation/cli.md
  - API:
      - Introduction: api/index.md
      # - Examples: api/examples.md
      - Reference v2: api/reference/v2/index.html
#  - Add-ons:
#     - Introduction: add-ons/index.md
#     - Documents:
#         - About: add-ons/documents/index.md
#         - Changelogs: add-ons/documents/changelogs.md
#  - Development Partners:
#     - Introduction: dev/index.md
  - Technical reference:
      - Version history: ref/version-history.md
      - Release Notes:
          - v2.0.0: ref/release-notes/v2.0.0.md
      - Changelog: ref/changelog.md
      - System Requirements: ref/system-requirements.md
  #     - License: ref/license.md
  #     - Database schema: ref/database-schema.md
  #     - List of collections: ref/list-of-collections.md
  #     - List of classes: ref/list-of-classes.md
  #     - List of categories: ref/list-of-categories.md
