---
blank_issues_enabled: false
contact_links:
  - name: Website
    url: https://docupike.com/
    about: The easy cloud based documentation
  - name: Docs
    url: https://docs.docupike.com/
    about: The easy cloud based documentation
  - name: Status
    url: https://status.docupike.com/
    about: Status page
  - name: Support
    url: mailto:help@docupike.com
    about: Customer support
  - name: Imprint
    url: https://docupike.com/legal/imprint
    about: Legal
  - name: Data protection
    url: https://docupike.com/legal/data-protection
    about: Legal
  - name: Terms & Conditions
    url: https://docupike.com/legal/terms-conditions
    about: Legal
  - name: GDPR
    url: https://docupike.com/legal/gdpr
    about: Legal
  - name: SLA
    url: https://docupike.com/legal/sla
    about: Legal
  - name: Services
    url: https://docupike.com/legal/services
    about: Legal
  - name: Security Policy
    url: https://docs.docupike.com/security.html
    about: Legal
