pipeline {
    agent any
    environment {
        USER_ID = "${sh(script: 'id -u', returnStdout: true).trim()}"
        GROUP_ID = "${sh(script: 'id -g', returnStdout: true).trim()}"
        REGISTRY_DOMAIN = 'registry.on.ops.docupike.net'
        REGISTRY_PREFIX = "${REGISTRY_DOMAIN}/"
        REGISTRY_CREDS = credentials('OPS_REGISTRY_CREDS')
        SSH_KEY_DOCS = '~/.ssh/id_ecdsa'
    }
    stages {
        stage('Pre-build') {
            steps {
                sh("docker-compose \
                    build \
                    --pull \
                    --build-arg USER_ID=${env.USER_ID} \
                    --build-arg GROUP_ID=${env.GROUP_ID} \
                ")
            }
        }
        stage('Install') {
            steps {
                sh('docker-compose run env npm install')
            }
        }
        stage('Build') {
            steps {
                sh('docker-compose run env npm run docs:build')
            }
        }
        stage('Deploy') {
            steps {
                sh('docker-compose run env npm run docs:deploy')
            }
        }
        stage('Push') {
            when {
                anyOf {
                    branch 'main'
                }
            }
            steps {
                sh('docker login \
                    --username $REGISTRY_CREDS_USR \
                    --password $REGISTRY_CREDS_PSW \
                    $REGISTRY_DOMAIN')
                sh('docker-compose push')
                sh('docker logout $REGISTRY_DOMAIN')
            }
        }
    }
    post {
        always {
            deleteDir()
        }
        failure {
            slackSend(channel: '#jenkins', color: 'danger', message: "FAILED - ${env.BUILD_URL}")
            slackSend(channel: '#monitoring-cloud', color: 'danger', message: "FAILED - ${env.BUILD_URL}")
        }
        unstable {
            slackSend(channel: '#jenkins', color: 'warning', message: "UNSTABLE - ${env.BUILD_URL}")
        }
        aborted {
            slackSend(channel: '#jenkins', color: 'danger', message: "ABORTED - ${env.BUILD_URL}")
        }
        fixed {
            slackSend(channel: '#jenkins', color: 'good', message: "BACK TO NORMAL - ${env.BUILD_URL}")
        }
    }
}
