---
name: Test docs

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install latest LTS version of Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Re-use NPM cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Pull container base image
        run: |
          docker-compose \
            -f docker-compose-ci.yml \
            pull
      - name: Re-use container image layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build container image
        run: |
          docker-compose \
            -f docker-compose-ci.yml \
            build \
            --build-arg USER_ID="$(id -u)" \
            --build-arg GROUP_ID="$(id -g)"
      - name: Install toolchain
        run: |
          docker-compose \
            -f docker-compose-ci.yml \
            run docs \
            npm install
      - name: Run tests
        run: |
          docker-compose \
            -f docker-compose-ci.yml \
            run docs \
            npm test
      - name: Build docs
        run: |
          docker-compose \
            -f docker-compose-ci.yml \
            run docs \
            npm run docs:build
